<html>
    <head>
        @include('common.head')
    </head>
    <body>
        @include('common.menu')
        @yield('page_content')
        @include('common.footer')
        @include('common.script')
        @yield('page_sctipt')
    </body>
</html>